application:
    build: docker/services/application
    volumes:
        - .:/var/www
    ports:
        - "80:80"
    links:
        - database
        - rabbitmq

database:
    build: docker/services/mariadb
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 4m81HGxH47i31Xw
        MYSQL_USER:          'znieh'
        MYSQL_PASSWORD:      'znieh'
        TERM: dumb
    volumes_from:
        - mariadbdata

rabbitmq:
    build: docker/services/rabbitmq
    environment:
    volumes:
        - /var/docker/rabbit:data
    ports:
        - "5672:5672"
        - "15672:15672"

mariadbdata:
    image: busybox:latest
    volumes:
        - /var/lib/mysql
    command: echo "I'm a data container"
