Znieh\Model\RuneType:
    type:  entity
    table: rune_types
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255

    oneToMany:
        objects:
            targetEntity: Rune
            mappedBy: type
