Znieh\Model\WeaponType:
    type:  entity
    table: weapon_types
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        image:
            type: string
            length: 255

    manyToMany:
        parts:
          targetEntity: WeaponPartType
          joinColumn:
            name: part_type_id
            referencedColumnName: id
          cascade: ["persist"]

    manyToOne:
        building:
          targetEntity: Building
          joinColumn:
            name: building_id
            referencedColumnName: id
