Znieh\Model\ArmorPartType:
  exclusion_policy: ALL
  properties:
    name:
      expose: true
      groups: [default, details]
    objects:
      expose: true
      groups: [details]
    type:
      expose: true
      groups: [details]
