Znieh\Model\GameObject:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      groups: [details]
    step:
      expose: true
      groups: [details]
    name:
      expose: true
      groups: [default, details]
    bonuses:
      expose: true
      groups: [default, details]
    points:
      expose: true
      groups: [default, details]
