Znieh\Model\ArmorPartType:
    type:  entity
    table: armor_part_types
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        type:
            type: string
            length: 255
        bonuses:
            type: array
        weight:
            type: integer
        defense:
            type: integer

    oneToMany:
        objects:
            targetEntity: ArmorPart
            mappedBy: type
