services:
  znieh_api.event.authentication_success_listener:
    class: AppBundle\EventListener\JWTResponseListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
