imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        dbname: %test_database_name%
        user:   %test_database_user%

swiftmailer:
    disable_delivery: true

lexik_jwt_authentication:
    private_key_path:   %kernel.root_dir%/var/jwt/private-test.pem
    public_key_path:    %kernel.root_dir%/var/jwt/public-test.pem
