security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
          ROLE_ADMIN:       ROLE_USER
          ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
                pattern:  ^/
                stateless: true
                anonymous: true
                form_login:
                    check_path: /login_check
                    require_previous_session: false
                    username_parameter: username
                    password_parameter: password
                    success_handler: lexik_jwt_authentication.handler.authentication_success
                    failure_handler: lexik_jwt_authentication.handler.authentication_failure
                lexik_jwt:
                   authorization_header: # check token in Authorization Header
                      enabled: true
                      prefix:  Bearer
                   query_parameter:      # check token in query string parameter
                      enabled: true
                      name:    bearer

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
