services:
  znieh_api.event.authentication_success_listener:
    class: AppBundle\EventListener\JWTResponseListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
  default_team.listener:
    class: AppBundle\EventListener\DefaultTeamListener
    tags:
      - { name: doctrine.event_listener, event: postPersist }
    arguments: ["@team_loader"]
  team_loader:
    class: Znieh\Loader\TeamLoader
  global_mailer:
    class: Znieh\Mailer\GlobalMailer
    arguments: [@hip_mandrill.dispatcher]
  email_registration_listener:
    class: AppBundle\EventListener\EmailRegistrationListener
    arguments: [@swarrot.publisher]
    tags:
      - { name: kernel.event_listener, event: email.registration, method: onEmailRegistration }
  email_registration.processor:
    class: AppBundle\Processor\EmailRegistrationProcessor
    arguments: [@global_mailer, @twig]
  currency_manager:
    class: Znieh\Currency\CurrencyManager
  team_update_listener:
    class: AppBundle\EventListener\TeamUpdateListener
    arguments: [@doctrine.orm.entity_manager]
    tags:
      - { name: kernel.event_listener, event: team.update, method: onTeamUpdate }
