Znieh\Model\ArmorPart:
  exclusion_policy: ALL
  properties:
    type:
      expose: true
      groups: [default, details]
    defense:
      expose: true
      groups: [default, details]
    weight:
      expose: true
      groups: [default, details]
