Znieh\Model\WeaponPart:
  exclusion_policy: ALL
  properties:
    name:
      expose: true
      groups: [default, details]
    minDamage:
      expose: true
      groups: [default, details]
    maxDamage:
      expose: true
      groups: [default, details]
