Znieh\Model\WeaponPartType:
  exclusion_policy: ALL
  properties:
    name:
      expose: true
      groups: [default, details]
    objects:
      expose: true
      groups: [details]
    # types:
    #   expose: true
    #   groups: [details]
